global:
    prompt: "a beautiful landscape"
    model_name_or_path_or_api_name: "6ce0161689"
    steps: 20
    sampler_name: Euler a
    cfg_scale: 7
    width: 512
    height: 512
    seed: -1

controlnet_units:
    - module: none
      model: None
      weight: 0.5
      start: 0.1
      end: 0.9

    - module: none
      model: None
      weight: 0.5
      start: 0.1
      end: 0.9

qrcode:
    text: "https://koll.ai"
    error_correction: high # [low, medium, quart, high]
    box_size: 10
    border: 4
    fill_color: black
    back_color: white
