global_params:
    steps: 20
    sampler: Euler a
    width: 512
    height: 512

controlnet_units:
    - unit1:
          module: "none"
          model: "None"
          weight: 0.5
          start: 0.1
          end: 0.9
    - unit1:
          module: "none"
          model: "None"
          weight: 0.5
          start: 0.1
          end: 0.9
